version: '3'
services:

  test_backend:
    build: .
    image: test_backend
    depends_on:
        - db
        - rabbit
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=backend_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - CELERY_BROKER=rabbit
      - SUPERUSER_NAME=user
      - SUPERUSER_PASSWORD=qwerty
      - ENV=PROD

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest

  celery:
    image: test_backend
    restart: always
    environment:
    - CELERY_BROKER=rabbit
    - DB_HOST=db
    - DB_NAME=backend_db
    - DB_USER=admin
    - DB_PASSWORD=admin
    depends_on:
      - rabbit
      - db
      - test_backend
    command: /bin/bash -c "exec celery -A test_backend worker -B"

  db:
    hostname: db
    image: kartoza/postgis
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend_db
