# Generated by Django 3.1.2 on 2020-10-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201006_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='geo',
            new_name='coordinates',
        ),
    ]
