# Generated by Django 3.1.2 on 2020-10-06 11:26

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=core.model_fields.PhoneNumberField(blank=True, max_length=12, null=True),
        ),
    ]
