# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Backend

on: [push, pull_request]


jobs:
  testing:
    env:
      DB_PORT: 3306
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: password
      NO_BUILD: 1
    runs-on: ubuntu-latest
    services:
      db:
        image: kartoza/postgis
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: backend_db

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run migrations
      run: |
        python3 manage.py migrate
    - name: Test
      run: |
        python3 manage.py test
